name: Build SushiNights

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow wave

    - name: Download ZGB-Linux-x64
      run: wget https://github.com/gbdk-2020/CrossZGB/releases/latest/download/ZGB-Linux-x64.tar.gz

    - name: Unpack ZGB-Linux-x64
      run: |
        tar -xzf ZGB-Linux-x64.tar.gz
        echo "GBDK_HOME=$(pwd)/CrossZGB/gbdk" >> $GITHUB_ENV
        echo "ZGB_PATH=$(pwd)/CrossZGB/ZGB/common" >> $GITHUB_ENV

    - name: Build project
      run: |
        cd src
        make
      env:
        GBDK_HOME: ${{ env.GBDK_HOME }}
        ZGB_PATH: ${{ env.ZGB_PATH }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SushiNights-ROM-files
        path: bin/

    - name: Delete old workflow runs
      uses: actions/github-script@v6
      with:
        script: |
          const runs = ${{ steps.get-runs.outputs.result }};
          const keepLatestRun = runs[0]; // Keep the latest successful run

          for (const run of runs) {
            if (run.id !== keepLatestRun.id) {
              await github.actions.deleteWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run.id
              });
            }
          }