name: Build SushiNights

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow wave

    - name: Download and unpack ZGB-Linux-x64
      run: |
        wget https://github.com/gbdk-2020/CrossZGB/releases/latest/download/ZGB-Linux-x64.tar.gz
        tar -xzf ZGB-Linux-x64.tar.gz
        echo "GBDK_HOME=$(pwd)/ZGB-Linux-x64/gbdk" >> $GITHUB_ENV
        echo "ZGB_PATH=$(pwd)/ZGB-Linux-x64/ZGB/common" >> $GITHUB_ENV

    - name: Build project
      run: |
        cd src
        make
      env:
        GBDK_HOME: ${{ env.GBDK_HOME }}
        ZGB_PATH: ${{ env.ZGB_PATH }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: bin/